name: Deploy React frontend to Azure Web App

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
        working-directory: frontend  # 👈 important !

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'frontend-oumouhou'  # remplace si nécessaire
          slot-name: 'Production'
          package: frontend/build        # 👈 important aussi !
